### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by HimbeerserverDE**
This PR adds `Dockerfile`s for regular and development builds as well as documentation (#132).

### CODE REVIEW

**Comment by AFCMS** [comment]
Looks like it works.

I would suggest publishing an image build on the GitHub container registry (or Docker Hub) using GitHub Actions.

For reference:
- https://docs.docker.com/build/ci/github-actions
- https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
- My skin server workflow: https://github.com/AFCMS/minetest-skin-server/blob/master/.github/workflows/build-image.yml Its building for arm with QEMU, but since Go support cross compilation i don't think its the ideal way to do. IDK I am making the dockerfile build right too.

Using this process will set most of the image metadata automatically according to Git and GitHub data using opencontainer's labels: https://github.com/opencontainers/image-spec/blob/main/annotations.md


Another thing I noticed is that the Dockerfile.devel file isn't recognized by GitHub, Goland and VSCode, while devel.Dockerfile is (but it doesn't make much sense IMO since it makes alphabetic file sorting useless)

**Comment by HimbeerserverDE** [comment]
What about these changes?

I set up cross-compilation (only amd64 and arm64 are built automatically) but I'm not sure if it's going to work in GitHub Actions. It may be necessary to do separate builds if Docker complains about the default building driver not supporting multi-platform (this happened locally during testing whenever I passed multiple targets to the same build command).

**Comment by AFCMS** [comment]
It seems to need the creation of a new docker builx context (don't know what GitHub Actions do). I didn't build everything with buildx, I have a bad network connection right now.

**Comment by HimbeerserverDE** [comment]
Is a context a builder instance? I can't find anything useful on "docker buildx context" in the documentation.

If it is, everything should work. I've successfully tested both Dockerfiles locally with buildx in its default configuration after installation.

It may be required to use the setup-buildx action to use the default driver or even install buildx in the first place.

I can't verify any of this without merging it or creating a testing repository. I'm going to try the latter tomorrow if it isn't too complicated.

**Comment by HimbeerserverDE** [comment]
As theorized in https://github.com/HimbeerserverDE/mt-multiserver-proxy/pull/144#issuecomment-1902058139 the amd64 and arm64 builds need to be done separately. Everything else seems to be working in the testing repository.

I will now merge this, check that it still works on this repository and fix the remaining issues if there are any.

**Pull request merged**
